# Generated by Django 3.0.8 on 2020-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(default=None),
        ),
    ]
